# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Rxswift_MVVM_RailsAPI_Bookshelf' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.5'
	pod 'AlamofireImage'
  pod 'SwiftyJSON'
	pod 'RxSwift'
  pod 'RxCocoa'
	pod 'RxOptional'''
	pod 'Action'
  # Pods for Rxswift_MVVM_RailsAPI_Bookshelf

end
